In [163]:
import pandas as pd

#### Load data

In [164]:
# load csv
test_set = pd.read_csv("../data/destinations_v5.csv", sep=";")

In [165]:
test_set

,City,Country,Category,Category 2,CO2,Distance (km),Flight time (min),Budget,Month,Average Temp,Sun hours per day,Rain probability
0,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,Jan,9.8,5.0,0.133333
1,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,Feb,10.3,6.0,0.133333
2,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,Mar,12.3,6.5,0.166667
3,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,Apr,14.5,7.5,0.166667
4,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,May,17.9,8.0,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...
235,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Aug,25.6,10.0,0.100000
236,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Sep,21.3,8.0,0.200000
237,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Oct,17.3,6.5,0.266667
238,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Nov,12.7,4.5,0.333333
239,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Dec,8.7,4.0,0.300000

In [166]:
season_dict = {
    'winter': ["Dec", "Jan", "Feb"],
    'spring': ["Mar", "Apr", "May"],
    'summer': ["Jun", "Jul", "Aug"],
    'autumn': ["Sep", "Oct", "Nov"]
}

#### Hard filter

In [167]:
travel_categories = test_set["Category"].unique()

user_activity = input( "Choose one of the travel categories:" + travel_categories)

user_season = input( "Which season?").lower()
user_months = season_dict[user_season]

In [205]:
test_set = test_set[test_set["Month"].isin(user_months)]
test_set

,City,Country,Category,Category 2,CO2,Distance (km),Flight time (min),Budget,Month,Average Temp,Sun hours per day,Rain probability
5,Barcelona,SP,Beach,Sightseeing,0.390,840,100,Medium,Jun,21.7,8.5,0.133333
6,Barcelona,SP,Beach,Sightseeing,0.390,840,100,Medium,Jul,24.5,10.0,0.066667
7,Barcelona,SP,Beach,Sightseeing,0.390,840,100,Medium,Aug,25.1,9.0,0.166667
17,Nice,FR,Beach,Sightseeing,0.280,420,70,Low,Jun,21.4,10.0,0.133333
18,Nice,FR,Beach,Sightseeing,0.280,420,70,Low,Jul,24.2,11.0,0.066667
19,Nice,FR,Beach,Sightseeing,0.280,420,70,Low,Aug,24.5,10.0,0.066667
29,Faro,PT,Beach,Party,0.660,1780,170,Low,Jun,22.1,11.0,0.033333
30,Faro,PT,Beach,Party,0.660,1780,170,Low,Jul,24.4,11.5,0.000000
31,Faro,PT,Beach,Party,0.660,1780,170,Low,Aug,24.4,11.0,0.000000
41,Paris,FR,Sightseeing,Sightseeing,0.290,490,85,Medium,Jun,18.2,6.5,0.300000
42,Paris,FR,Sightseeing,Sightseeing,0.290,490,85,Medium,Jul,20.5,7.0,0.266667
43,Paris,FR,Sightseeing,Sightseeing,0.290,490,85,Medium,Aug,20.2,7.0,0.233333
53,Amsterdam,NL,Sightseeing,Party,0.320,610,100,Low,Jun,15.8,7.0,0.333333
54,Amsterdam,NL,Sightseeing,Party,0.320,610,100,Low,Jul,18.0,7.5,0.366667
55,Amsterdam,NL,Sightseeing,Party,0.320,610,100,Low,Aug,17.8,6.5,0.400000
65,London,UK,Sightseeing,Sightseeing,0.370,780,110,High,Jun,16.8,7.0,0.266667
66,London,UK,Sightseeing,Sightseeing,0.370,780,110,High,Jul,19.0,7.0,0.266667
67,London,UK,Sightseeing,Sightseeing,0.370,780,110,High,Aug,18.7,6.5,0.266667
77,Oslo,NO,Outdoor,Sightseeing,0.540,1400,135,High,Jun,15.6,8.0,0.333333
78,Oslo,NO,Outdoor,Sightseeing,0.540,1400,135,High,Jul,18.0,8.0,0.366667
79,Oslo,NO,Outdoor,Sightseeing,0.540,1400,135,High,Aug,16.9,6.5,0.366667
89,Reykjavik,ISL,Outdoor,Outdoor,0.929,2620,225,High,Jun,10.1,6.0,0.300000
90,Reykjavik,ISL,Outdoor,Outdoor,0.929,2620,225,High,Jul,12.0,5.5,0.333333
91,Reykjavik,ISL,Outdoor,Outdoor,0.929,2620,225,High,Aug,11.4,5.0,0.400000
101,Edinburgh,UK,Outdoor,Sightseeing,0.493,1250,135,Medium,Jun,13.1,5.5,0.333333
102,Edinburgh,UK,Outdoor,Sightseeing,0.493,1250,135,Medium,Jul,14.8,5.5,0.366667
103,Edinburgh,UK,Outdoor,Sightseeing,0.493,1250,135,Medium,Aug,14.7,5.0,0.333333
113,Prag,CZ,Party,Sightseeing,0.300,530,80,Low,Jun,16.5,7.5,0.333333
114,Prag,CZ,Party,Sightseeing,0.300,530,80,Low,Jul,18.7,7.5,0.300000
115,Prag,CZ,Party,Sightseeing,0.300,530,80,Low,Aug,18.5,7.0,0.300000
125,Rimini,IT,Party,Beach,0.290,480,70,Medium,Jun,21.6,8.5,0.200000
126,Rimini,IT,Party,Beach,0.290,480,70,Medium,Jul,24.2,9.5,0.133333
127,Rimini,IT,Party,Beach,0.290,480,70,Medium,Aug,24.1,8.5,0.200000
137,Ibiza,SP,Party,Beach,0.460,1100,125,High,Jun,22.8,10.0,0.100000
138,Ibiza,SP,Party,Beach,0.460,1100,125,High,Jul,25.6,11.0,0.033333
139,Ibiza,SP,Party,Beach,0.460,1100,125,High,Aug,26.4,10.0,0.100000
149,Crete,GR,Beach,Beach,0.704,1919,180,Medium,Jun,23.6,12.0,0.000000
150,Crete,GR,Beach,Beach,0.704,1919,180,Medium,Jul,26.0,12.0,0.000000
151,Crete,GR,Beach,Beach,0.704,1919,180,Medium,Aug,26.2,11.0,0.000000
161,Split,HR,Beach,Party,0.360,751,100,Low,Jun,24.1,10.5,0.166667
162,Split,HR,Beach,Party,0.360,751,100,Low,Jul,16.9,11.5,0.100000
163,Split,HR,Beach,Party,0.360,751,100,Low,Aug,26.9,11.0,0.100000
173,Budapest,HU,Party,Sightseeing,0.380,790,100,Low,Jun,19.5,9.0,0.233333
174,Budapest,HU,Party,Sightseeing,0.380,790,100,Low,Jul,21.4,9.5,0.200000
175,Budapest,HU,Party,Sightseeing,0.380,790,100,Low,Aug,21.3,9.0,0.200000
185,Krakow,PL,Party,Sightseeing,0.390,890,100,Low,Jun,17.7,6.5,0.300000
186,Krakow,PL,Party,Sightseeing,0.390,890,100,Low,Jul,19.6,7.0,0.366667
187,Krakow,PL,Party,Sightseeing,0.390,890,100,Low,Aug,19.2,6.5,0.266667
197,Chamonix,FR,Outdoor,Sightseeing,0.220,200,120,Medium,Jun,15.1,7.5,0.433333
198,Chamonix,FR,Outdoor,Sightseeing,0.220,200,120,Medium,Jul,16.8,8.0,0.400000
199,Chamonix,FR,Outdoor,Sightseeing,0.220,200,120,Medium,Aug,16.4,7.5,0.400000
209,Tirana,AL,Outdoor,Beach,0.460,1120,120,Low,Jun,23.0,10.0,0.166667
210,Tirana,AL,Outdoor,Beach,0.460,1120,120,Low,Jul,25.3,11.5,0.133333
211,Tirana,AL,Outdoor,Beach,0.460,1120,120,Low,Aug,25.5,10.5,0.100000
221,Lisbon,PT,Sightseeing,Beach,0.640,1720,170,Medium,Jun,21.3,10.0,0.066667
222,Lisbon,PT,Sightseeing,Beach,0.640,1720,170,Medium,Jul,23.1,11.5,0.033333
223,Lisbon,PT,Sightseeing,Beach,0.640,1720,170,Medium,Aug,23.6,11.0,0.033333
233,Rome,IT,Sightseeing,Sightseeing,0.350,680,90,Medium,Jun,22.4,10.0,0.133333
234,Rome,IT,Sightseeing,Sightseeing,0.350,680,90,Medium,Jul,25.2,11.0,0.066667
235,Rome,IT,Sightseeing,Sightseeing,0.350,680,90,Medium,Aug,25.6,10.0,0.100000

In [171]:
test_set_clean = test_set.groupby(["City", "Category", "Category 2", "Budget"]).mean()
test_set_clean

,,,,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
City,Category,Category 2,Budget,,,,,,
Amsterdam,Sightseeing,Party,Low,0.320,610,100,17.200000,7.000000,0.366667
Barcelona,Beach,Sightseeing,Medium,0.390,840,100,23.766667,9.166667,0.122222
Budapest,Party,Sightseeing,Low,0.380,790,100,20.733333,9.166667,0.211111
Chamonix,Outdoor,Sightseeing,Medium,0.220,200,120,16.100000,7.666667,0.411111
Crete,Beach,Beach,Medium,0.704,1919,180,25.266667,11.666667,0.000000
Edinburgh,Outdoor,Sightseeing,Medium,0.493,1250,135,14.200000,5.333333,0.344444
Faro,Beach,Party,Low,0.660,1780,170,23.633333,11.166667,0.011111
Ibiza,Party,Beach,High,0.460,1100,125,24.933333,10.333333,0.077778
Krakow,Party,Sightseeing,Low,0.390,890,100,18.833333,6.666667,0.311111
Lisbon,Sightseeing,Beach,Medium,0.640,1720,170,22.666667,10.833333,0.044444
London,Sightseeing,Sightseeing,High,0.370,780,110,18.166667,6.833333,0.266667
Nice,Beach,Sightseeing,Low,0.280,420,70,23.366667,10.333333,0.088889
Oslo,Outdoor,Sightseeing,High,0.540,1400,135,16.833333,7.500000,0.355556
Paris,Sightseeing,Sightseeing,Medium,0.290,490,85,19.633333,6.833333,0.266667
Prag,Party,Sightseeing,Low,0.300,530,80,17.900000,7.333333,0.311111
Reykjavik,Outdoor,Outdoor,High,0.929,2620,225,11.166667,5.500000,0.344444
Rimini,Party,Beach,Medium,0.290,480,70,23.300000,8.833333,0.177778
Rome,Sightseeing,Sightseeing,Medium,0.350,680,90,24.400000,10.333333,0.100000
Split,Beach,Party,Low,0.360,751,100,22.633333,11.000000,0.122222
Tirana,Outdoor,Beach,Low,0.460,1120,120,24.600000,10.666667,0.133333

In [172]:
test_set_clean = test_set_clean.reset_index()
test_set_clean

,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
0,Amsterdam,Sightseeing,Party,Low,0.320,610,100,17.200000,7.000000,0.366667
1,Barcelona,Beach,Sightseeing,Medium,0.390,840,100,23.766667,9.166667,0.122222
2,Budapest,Party,Sightseeing,Low,0.380,790,100,20.733333,9.166667,0.211111
3,Chamonix,Outdoor,Sightseeing,Medium,0.220,200,120,16.100000,7.666667,0.411111
4,Crete,Beach,Beach,Medium,0.704,1919,180,25.266667,11.666667,0.000000
5,Edinburgh,Outdoor,Sightseeing,Medium,0.493,1250,135,14.200000,5.333333,0.344444
6,Faro,Beach,Party,Low,0.660,1780,170,23.633333,11.166667,0.011111
7,Ibiza,Party,Beach,High,0.460,1100,125,24.933333,10.333333,0.077778
8,Krakow,Party,Sightseeing,Low,0.390,890,100,18.833333,6.666667,0.311111
9,Lisbon,Sightseeing,Beach,Medium,0.640,1720,170,22.666667,10.833333,0.044444
10,London,Sightseeing,Sightseeing,High,0.370,780,110,18.166667,6.833333,0.266667
11,Nice,Beach,Sightseeing,Low,0.280,420,70,23.366667,10.333333,0.088889
12,Oslo,Outdoor,Sightseeing,High,0.540,1400,135,16.833333,7.500000,0.355556
13,Paris,Sightseeing,Sightseeing,Medium,0.290,490,85,19.633333,6.833333,0.266667
14,Prag,Party,Sightseeing,Low,0.300,530,80,17.900000,7.333333,0.311111
15,Reykjavik,Outdoor,Outdoor,High,0.929,2620,225,11.166667,5.500000,0.344444
16,Rimini,Party,Beach,Medium,0.290,480,70,23.300000,8.833333,0.177778
17,Rome,Sightseeing,Sightseeing,Medium,0.350,680,90,24.400000,10.333333,0.100000
18,Split,Beach,Party,Low,0.360,751,100,22.633333,11.000000,0.122222
19,Tirana,Outdoor,Beach,Low,0.460,1120,120,24.600000,10.666667,0.133333

In [173]:
# filter for user category in both category columns
# watch out, user has to pass 'user_category' first!
test_set_clean = test_set_clean[(test_set_clean["Category"] == user_activity) | (test_set_clean["Category 2"] == user_activity)]
test_set_clean = test_set_clean.reset_index()
test_set_clean

,index,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
0,1,Barcelona,Beach,Sightseeing,Medium,0.390,840,100,23.766667,9.166667,0.122222
1,4,Crete,Beach,Beach,Medium,0.704,1919,180,25.266667,11.666667,0.000000
2,6,Faro,Beach,Party,Low,0.660,1780,170,23.633333,11.166667,0.011111
3,7,Ibiza,Party,Beach,High,0.460,1100,125,24.933333,10.333333,0.077778
4,9,Lisbon,Sightseeing,Beach,Medium,0.640,1720,170,22.666667,10.833333,0.044444
5,11,Nice,Beach,Sightseeing,Low,0.280,420,70,23.366667,10.333333,0.088889
6,16,Rimini,Party,Beach,Medium,0.290,480,70,23.300000,8.833333,0.177778
7,18,Split,Beach,Party,Low,0.360,751,100,22.633333,11.000000,0.122222
8,19,Tirana,Outdoor,Beach,Low,0.460,1120,120,24.600000,10.666667,0.133333

#### User parameters questionnaire (input)

In [176]:
preferences_dict = {
    1: {"category": "Budget", 
        "weight": 0},
    2: {"category": "Flight time", 
        "weight": 0},
    3: {"category": "CO2",
        "weight": 0},
    4: {"category": "Temperature",
        "weight": 0},
    5: {"category": "Rain probability",
        "weight": 0}
}

In [177]:
i = 0
start_weight = 30
preferences_list = []
options_list = list( range(1,6) )
while i < 4:
    try: #the try statement runs the normal entry of 10 floats (question does not specify in float or integer, thus assume float)
        # print("Please state the number (e.g. 1) of your preference out of the remaining categories:\n")
        print(options_list)
        
        for count, option in enumerate(options_list):
            # print(count)
            print( "\t" + str(option) + "\t" + str(preferences_dict[options_list[count]]["category"]) + "\n")
            
        preference = int(input(f'Enter your preference {i+1} out of ' + str(options_list)))
        if (preference in options_list):
            options_list.remove(preference) 
            preferences_list.append(preference)
            preferences_dict[preference]["weight"] = start_weight
            start_weight -= 5
            i += 1 
            if len(preferences_list) == 4:
                preferences_dict[options_list[0]]["weight"] = start_weight
                preferences_list.append(options_list[0]) 
        else:
            print('You have to enter a number out of', options_list)

    except ValueError: #the except statement is triggered whenever a number is not entered
        print('You entered a string. Try again.')
print(f'\nYour preferences are: {preferences_dict[preferences_list[0]]["category"], preferences_dict[preferences_list[1]]["category"], preferences_dict[preferences_list[2]]["category"], preferences_dict[preferences_list[3]]["category"], preferences_dict[preferences_list[4]]["category"]}') #prints the final sum of all 10 entered integers

[1, 2, 3, 4, 5]
	1	Budget

	2	Flight time

	3	CO2

	4	Temperature

	5	Rain probability

[2, 3, 4, 5]
	2	Flight time

	3	CO2

	4	Temperature

	5	Rain probability

[3, 4, 5]
	3	CO2

	4	Temperature

	5	Rain probability

[4, 5]
	4	Temperature

	5	Rain probability


Your preferences are: ('Budget', 'Flight time', 'CO2', 'Temperature', 'Rain probability')

In [178]:
preferences_dict

{1: {'category': 'Budget', 'weight': 30},
 2: {'category': 'Flight time', 'weight': 25},
 3: {'category': 'CO2', 'weight': 20},
 4: {'category': 'Temperature', 'weight': 15},
 5: {'category': 'Rain probability', 'weight': 10}}

In [284]:
# previous implementation (causes copy problems)
# df_scores = pd.DataFrame(columns=[test_set_clean.columns], index=test_set_clean.index).copy()
# df_scores[["City", "Category", "Category 2", "Budget"]] = test_set_clean[["City", "Category", "Category 2", "Budget"]].copy()

df_scores = test_set_clean.copy()
df_scores

,index,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
0,1,Barcelona,Beach,Sightseeing,Medium,0.390,840,100,23.766667,9.166667,0.122222
1,4,Crete,Beach,Beach,Medium,0.704,1919,180,25.266667,11.666667,0.000000
2,6,Faro,Beach,Party,Low,0.660,1780,170,23.633333,11.166667,0.011111
3,7,Ibiza,Party,Beach,High,0.460,1100,125,24.933333,10.333333,0.077778
4,9,Lisbon,Sightseeing,Beach,Medium,0.640,1720,170,22.666667,10.833333,0.044444
5,11,Nice,Beach,Sightseeing,Low,0.280,420,70,23.366667,10.333333,0.088889
6,16,Rimini,Party,Beach,Medium,0.290,480,70,23.300000,8.833333,0.177778
7,18,Split,Beach,Party,Low,0.360,751,100,22.633333,11.000000,0.122222
8,19,Tirana,Outdoor,Beach,Low,0.460,1120,120,24.600000,10.666667,0.133333

In [285]:
for x in ["CO2", "Flight time (min)", "Rain probability"]:
    for i in range(0, len(df_scores)):
        if test_set_clean.loc[i, x] <= test_set_clean[x].median():
            df_scores.loc[i, x] = 1
        else: 
            df_scores.loc[i, x] = 0

for y in ["Average Temp", "Sun hours per day"]:
    for j in range(0, len(df_scores)):
        if test_set_clean.loc[j, y] >= test_set_clean[y].median():
            df_scores.loc[j, y] = 1
        else: 
            df_scores.loc[j, y] = 0

replace_dic = {"Low": "1", "Medium": 0.5, "High": 0}
df_scores["Budget"].replace(replace_dic, inplace = True)

# previous implementation:
# df_scores['Budget'] = df_scores['Budget'].replace("Low", 1)
# df_scores['Budget'] = df_scores['Budget'].replace("Medium", 0.5)
# df_scores['Budget'] = df_scores['Budget'].replace("High", 0)

df_scores

,index,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
0,1,Barcelona,Beach,Sightseeing,0.5,1.0,840,1,1.0,0.0,0.0
1,4,Crete,Beach,Beach,0.5,0.0,1919,0,1.0,1.0,1.0
2,6,Faro,Beach,Party,1,0.0,1780,0,1.0,1.0,1.0
3,7,Ibiza,Party,Beach,0,1.0,1100,0,1.0,0.0,1.0
4,9,Lisbon,Sightseeing,Beach,0.5,0.0,1720,0,0.0,1.0,1.0
5,11,Nice,Beach,Sightseeing,1,1.0,420,1,0.0,0.0,1.0
6,16,Rimini,Party,Beach,0.5,1.0,480,1,0.0,0.0,0.0
7,18,Split,Beach,Party,1,1.0,751,1,0.0,1.0,0.0
8,19,Tirana,Outdoor,Beach,1,1.0,1120,1,1.0,1.0,0.0

In [286]:
score_budget = preferences_dict[1]["weight"] * df_scores["Budget"]
score_flight_time = preferences_dict[2]["weight"] * df_scores["Flight time (min)"]
score_co2 = preferences_dict[3]["weight"] * df_scores["CO2"]
score_temp = preferences_dict[4]["weight"] * df_scores["Average Temp"]
score_rain = preferences_dict[5]["weight"] * df_scores["Rain probability"]

df_scores["Score"] = pd.concat([score_budget, score_flight_time, score_co2, score_temp, score_rain], axis=1).sum(axis=1)
df_scores

,index,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability,Score
0,1,Barcelona,Beach,Sightseeing,0.5,1.0,840,1,1.0,0.0,0.0,60.0
1,4,Crete,Beach,Beach,0.5,0.0,1919,0,1.0,1.0,1.0,25.0
2,6,Faro,Beach,Party,1,0.0,1780,0,1.0,1.0,1.0,25.0
3,7,Ibiza,Party,Beach,0,1.0,1100,0,1.0,0.0,1.0,45.0
4,9,Lisbon,Sightseeing,Beach,0.5,0.0,1720,0,0.0,1.0,1.0,10.0
5,11,Nice,Beach,Sightseeing,1,1.0,420,1,0.0,0.0,1.0,55.0
6,16,Rimini,Party,Beach,0.5,1.0,480,1,0.0,0.0,0.0,45.0
7,18,Split,Beach,Party,1,1.0,751,1,0.0,1.0,0.0,45.0
8,19,Tirana,Outdoor,Beach,1,1.0,1120,1,1.0,1.0,0.0,60.0

In [288]:
# sort according to Score
df_scores.sort_values(by=['Score'], ascending = False, inplace = True)
df_scores["index"] = df_scores.reset_index().index
df_scores["index"] += 1
df_scores.rename({"index": "Rank"}, axis=1, inplace=True)
df_scores = df_scores.set_index("Rank")
df_scores

,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability,Score
Rank,,,,,,,,,,,
1,Barcelona,Beach,Sightseeing,0.5,1.0,840,1,1.0,0.0,0.0,60.0
2,Tirana,Outdoor,Beach,1,1.0,1120,1,1.0,1.0,0.0,60.0
3,Nice,Beach,Sightseeing,1,1.0,420,1,0.0,0.0,1.0,55.0
4,Ibiza,Party,Beach,0,1.0,1100,0,1.0,0.0,1.0,45.0
5,Rimini,Party,Beach,0.5,1.0,480,1,0.0,0.0,0.0,45.0
6,Split,Beach,Party,1,1.0,751,1,0.0,1.0,0.0,45.0
7,Crete,Beach,Beach,0.5,0.0,1919,0,1.0,1.0,1.0,25.0
8,Faro,Beach,Party,1,0.0,1780,0,1.0,1.0,1.0,25.0
9,Lisbon,Sightseeing,Beach,0.5,0.0,1720,0,0.0,1.0,1.0,10.0

In [300]:
print("Your top 3 travel locations are: \n", df_scores.loc[1:3, ["City", "Score"]])

Your top 3 travel locations are:
            City  Score
Rank
1     Barcelona   60.0
2        Tirana   60.0
3          Nice   55.0