In [1]:
import pandas as pd

#### Load data

In [2]:
# load csv
test_set = pd.read_csv("../data/destinations_v5.csv", sep=";")

In [3]:
test_set

,City,Country,Category,Category 2,CO2,Distance (km),Flight time (min),Budget,Month,Average Temp,Sun hours per day,Rain probability
0,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,Jan,9.8,5.0,0.133333
1,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,Feb,10.3,6.0,0.133333
2,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,Mar,12.3,6.5,0.166667
3,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,Apr,14.5,7.5,0.166667
4,Barcelona,SP,Beach,Sightseeing,0.39,840,100,Medium,May,17.9,8.0,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...
235,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Aug,25.6,10.0,0.100000
236,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Sep,21.3,8.0,0.200000
237,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Oct,17.3,6.5,0.266667
238,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Nov,12.7,4.5,0.333333
239,Rome,IT,Sightseeing,Sightseeing,0.35,680,90,Medium,Dec,8.7,4.0,0.300000

In [4]:
season_dict = {
    'winter': ["Dec", "Jan", "Feb"],
    'spring': ["Mar", "Apr", "May"],
    'summer': ["Jun", "Jul", "Aug"],
    'autumn': ["Sep", "Oct", "Nov"]
}

#### GUI set up

In [5]:
# Set up the basics

import tkinter as tk
from tkinter import ttk
from ctypes import windll
from tkinter.messagebox import showinfo
windll.shcore.SetProcessDpiAwareness(1)

root = tk.Tk()
root.title("Travel Planner")
root.geometry('1500x1000+50+50')
root.attributes('-topmost', 1)

# Place a label on the root window
message = tk.Label(root, text="This is your travel planner!") #This creates a widget
message.pack() #This unpacks the widget to the main window

In [6]:
# Create the first option

selected_type = tk.StringVar()
types = (('Sightseeing', 'Sightseeing'),
         ('Outdoor', 'Outdoor'),
         ('Beach', 'Beach'),
         ('Party', 'Party'))

label_type = ttk.Label(text="What's your favourite type of holiday?")
label_type.pack(fill='x', padx=5, pady=5)


for type in types:
    t = ttk.Radiobutton(
        root,
        text=type[0],
        value=type[1],
        variable=selected_type
    )
    t.pack(fill='x', padx=5, pady=5)

separator_1 = ttk.Separator(root, orient='horizontal')
separator_1.pack(fill='x')

In [7]:
# Create the second option

selected_season = tk.StringVar()
seasons = (('Winter', 'winter'),
         ('Spring', 'spring'),
         ('Summer', 'summer'),
         ('Autumn', 'autumn'))

label_season = ttk.Label(text="In which season do you want to travel?")
label_season.pack(fill='x', padx=5, pady=5)

for season in seasons:
    s = ttk.Radiobutton(
        root,
        text=season[0],
        value=season[1],
        variable=selected_season
    )
    s.pack(fill='x', padx=5, pady=5)

separator_1 = ttk.Separator(root, orient='horizontal')
separator_1.pack(fill='x')

In [8]:
# Create the ranking in Python

message_2 = tk.Label(root, text="Please select the priorities for your travel planner") #This creates a widget
message_2.pack() #This unpacks the widget to the main window

# Label 1
label_ranking = ttk.Label(text="Please select your first priority:")
label_ranking.pack(fill=tk.X, padx=5, pady=5)


selected_priority_1 = tk.StringVar()
selected_priority_2 = tk.StringVar()
selected_priority_3 = tk.StringVar()
selected_priority_4 = tk.StringVar()
selected_priority_5 = tk.StringVar()

# Create Combobox
priorities = ('Budget',
                'Flight time',
                'CO2',
                'Temperature',
                'Rain probability'
            )

rankings_1 = ttk.Combobox(textvariable = selected_priority_1,
                          state = "readonly",
                          values = priorities)

rankings_1.current(0) 
rankings_1.pack()

# Label 2
label_ranking = ttk.Label(text="Please select your second priority:")
label_ranking.pack(fill=tk.X, padx=5, pady=5)

rankings_2 = ttk.Combobox(textvariable = selected_priority_2,
                          state = "readonly",
                          values = priorities)

rankings_2.current(0) 
rankings_2.pack()

# Label 3
label_ranking = ttk.Label(text="Please select your third priority:")
label_ranking.pack(fill=tk.X, padx=5, pady=5)

rankings_3 = ttk.Combobox(textvariable = selected_priority_3,
                          state = "readonly",
                          values = priorities)

rankings_3.current(0) 
rankings_3.pack()

# Label 4
label_ranking = ttk.Label(text="Please select your fourth priority:")
label_ranking.pack(fill=tk.X, padx=5, pady=5)

rankings_4 = ttk.Combobox(textvariable = selected_priority_4,
                          state = "readonly",
                          values = priorities)

rankings_4.current(0) 
rankings_4.pack()

# Label 5
label_ranking = ttk.Label(text="Please select your fifth priority:")
label_ranking.pack(fill=tk.X, padx=5, pady=5)

rankings_5 = ttk.Combobox(textvariable = selected_priority_5,
                          state = "readonly",
                          values = priorities)

rankings_5.current(0) 
rankings_5.pack()

In [9]:
# submit button

submit_button = ttk.Button(root, text="Submit", command=root.destroy)
submit_button.pack(ipadx=5,
    ipady=5,
    expand=True
)

In [10]:
# keep the window displaying

root.mainloop()

user_activity = selected_type.get()
user_season = selected_season.get()
user_prio1 = selected_priority_1.get()
user_prio2 = selected_priority_2.get()
user_prio3 = selected_priority_3.get()
user_prio4 = selected_priority_4.get()
user_prio5 = selected_priority_5.get()

In [11]:
print(user_activity)
print(user_season)
print(user_prio1)
print(user_prio2)
print(user_prio3)
print(user_prio4)
print(user_prio5)

Sightseeing
spring
Flight time
Budget
CO2
Temperature
Rain probability

#### Filtering

In [12]:
user_months = season_dict[user_season]
user_months

['Mar', 'Apr', 'May']

In [13]:
test_set = test_set[test_set["Month"].isin(user_months)]
test_set

,City,Country,Category,Category 2,CO2,Distance (km),Flight time (min),Budget,Month,Average Temp,Sun hours per day,Rain probability
2,Barcelona,SP,Beach,Sightseeing,0.390,840,100,Medium,Mar,12.3,6.5,0.166667
3,Barcelona,SP,Beach,Sightseeing,0.390,840,100,Medium,Apr,14.5,7.5,0.166667
4,Barcelona,SP,Beach,Sightseeing,0.390,840,100,Medium,May,17.9,8.0,0.166667
14,Nice,FR,Beach,Sightseeing,0.280,420,70,Low,Mar,11.9,7.0,0.166667
15,Nice,FR,Beach,Sightseeing,0.280,420,70,Low,Apr,14.1,7.5,0.233333
16,Nice,FR,Beach,Sightseeing,0.280,420,70,Low,May,17.8,8.5,0.166667
26,Faro,PT,Beach,Party,0.660,1780,170,Low,Mar,14.8,8.0,0.166667
27,Faro,PT,Beach,Party,0.660,1780,170,Low,Apr,16.4,8.5,0.166667
28,Faro,PT,Beach,Party,0.660,1780,170,Low,May,19.1,10.0,0.166667
38,Paris,FR,Sightseeing,Sightseeing,0.290,490,85,Medium,Mar,8.3,4.0,0.333333
39,Paris,FR,Sightseeing,Sightseeing,0.290,490,85,Medium,Apr,11.3,5.5,0.300000
40,Paris,FR,Sightseeing,Sightseeing,0.290,490,85,Medium,May,14.9,6.5,0.333333
50,Amsterdam,NL,Sightseeing,Party,0.320,610,100,Low,Mar,6.4,4.5,0.333333
51,Amsterdam,NL,Sightseeing,Party,0.320,610,100,Low,Apr,9.7,6.5,0.300000
52,Amsterdam,NL,Sightseeing,Party,0.320,610,100,Low,May,13.2,7.5,0.300000
62,London,UK,Sightseeing,Sightseeing,0.370,780,110,High,Mar,8.0,4.0,0.266667
63,London,UK,Sightseeing,Sightseeing,0.370,780,110,High,Apr,10.6,6.0,0.300000
64,London,UK,Sightseeing,Sightseeing,0.370,780,110,High,May,13.8,6.5,0.266667
74,Oslo,NO,Outdoor,Sightseeing,0.540,1400,135,High,Mar,1.6,4.5,0.233333
75,Oslo,NO,Outdoor,Sightseeing,0.540,1400,135,High,Apr,6.5,6.0,0.266667
76,Oslo,NO,Outdoor,Sightseeing,0.540,1400,135,High,May,11.7,8.0,0.300000
86,Reykjavik,ISL,Outdoor,Outdoor,0.929,2620,225,High,Mar,1.2,3.5,0.466667
87,Reykjavik,ISL,Outdoor,Outdoor,0.929,2620,225,High,Apr,3.9,5.5,0.366667
88,Reykjavik,ISL,Outdoor,Outdoor,0.929,2620,225,High,May,6.9,6.5,0.333333
98,Edinburgh,UK,Outdoor,Sightseeing,0.493,1250,135,Medium,Mar,5.6,4.0,0.333333
99,Edinburgh,UK,Outdoor,Sightseeing,0.493,1250,135,Medium,Apr,7.6,5.0,0.300000
100,Edinburgh,UK,Outdoor,Sightseeing,0.493,1250,135,Medium,May,10.3,6.5,0.333333
110,Prag,CZ,Party,Sightseeing,0.300,530,80,Low,Mar,4.1,4.0,0.200000
111,Prag,CZ,Party,Sightseeing,0.300,530,80,Low,Apr,8.9,5.5,0.233333
112,Prag,CZ,Party,Sightseeing,0.300,530,80,Low,May,13.1,7.0,0.333333
122,Rimini,IT,Party,Beach,0.290,480,70,Medium,Mar,8.9,5.0,0.200000
123,Rimini,IT,Party,Beach,0.290,480,70,Medium,Apr,12.4,5.5,0.233333
124,Rimini,IT,Party,Beach,0.290,480,70,Medium,May,17.2,7.0,0.233333
134,Ibiza,SP,Party,Beach,0.460,1100,125,High,Mar,13.6,7.0,0.200000
135,Ibiza,SP,Party,Beach,0.460,1100,125,High,Apr,15.8,8.0,0.200000
136,Ibiza,SP,Party,Beach,0.460,1100,125,High,May,18.8,9.0,0.166667
146,Crete,GR,Beach,Beach,0.704,1919,180,Medium,Mar,13.8,6.0,0.200000
147,Crete,GR,Beach,Beach,0.704,1919,180,Medium,Apr,16.3,8.0,0.100000
148,Crete,GR,Beach,Beach,0.704,1919,180,Medium,May,19.8,9.5,0.066667
158,Split,HR,Beach,Party,0.360,751,100,Low,Mar,11.4,6.0,0.233333
159,Split,HR,Beach,Party,0.360,751,100,Low,Apr,15.0,7.5,0.266667
160,Split,HR,Beach,Party,0.360,751,100,Low,May,19.9,9.0,0.200000
170,Budapest,HU,Party,Sightseeing,0.380,790,100,Low,Mar,5.6,5.0,0.200000
171,Budapest,HU,Party,Sightseeing,0.380,790,100,Low,Apr,11.1,7.0,0.200000
172,Budapest,HU,Party,Sightseeing,0.380,790,100,Low,May,15.7,8.5,0.266667
182,Krakow,PL,Party,Sightseeing,0.390,890,100,Low,Mar,3.8,3.0,0.300000
183,Krakow,PL,Party,Sightseeing,0.390,890,100,Low,Apr,9.4,4.5,0.266667
184,Krakow,PL,Party,Sightseeing,0.390,890,100,Low,May,14.2,6.5,0.333333
194,Chamonix,FR,Outdoor,Sightseeing,0.220,200,120,Medium,Mar,3.9,5.5,0.333333
195,Chamonix,FR,Outdoor,Sightseeing,0.220,200,120,Medium,Apr,7.4,5.5,0.333333
196,Chamonix,FR,Outdoor,Sightseeing,0.220,200,120,Medium,May,11.8,6.5,0.466667
206,Tirana,AL,Outdoor,Beach,0.460,1120,120,Low,Mar,11.3,5.5,0.366667
207,Tirana,AL,Outdoor,Beach,0.460,1120,120,Low,Apr,14.6,6.5,0.333333
208,Tirana,AL,Outdoor,Beach,0.460,1120,120,Low,May,18.7,8.5,0.300000
218,Lisbon,PT,Sightseeing,Beach,0.640,1720,170,Medium,Mar,14.8,6.5,0.266667
219,Lisbon,PT,Sightseeing,Beach,0.640,1720,170,Medium,Apr,16.2,8.0,0.266667
220,Lisbon,PT,Sightseeing,Beach,0.640,1720,170,Medium,May,18.5,9.5,0.166667
230,Rome,IT,Sightseeing,Sightseeing,0.350,680,90,Medium,Mar,10.9,6.0,0.233333
231,Rome,IT,Sightseeing,Sightseeing,0.350,680,90,Medium,Apr,13.8,7.0,0.300000
232,Rome,IT,Sightseeing,Sightseeing,0.350,680,90,Medium,May,17.9,9.0,0.200000

In [14]:
test_set_clean = test_set.groupby(["City", "Category", "Category 2", "Budget"]).mean()
test_set_clean

,,,,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
City,Category,Category 2,Budget,,,,,,
Amsterdam,Sightseeing,Party,Low,0.320,610,100,9.766667,6.166667,0.311111
Barcelona,Beach,Sightseeing,Medium,0.390,840,100,14.900000,7.333333,0.166667
Budapest,Party,Sightseeing,Low,0.380,790,100,10.800000,6.833333,0.222222
Chamonix,Outdoor,Sightseeing,Medium,0.220,200,120,7.700000,5.833333,0.377778
Crete,Beach,Beach,Medium,0.704,1919,180,16.633333,7.833333,0.122222
Edinburgh,Outdoor,Sightseeing,Medium,0.493,1250,135,7.833333,5.166667,0.322222
Faro,Beach,Party,Low,0.660,1780,170,16.766667,8.833333,0.166667
Ibiza,Party,Beach,High,0.460,1100,125,16.066667,8.000000,0.188889
Krakow,Party,Sightseeing,Low,0.390,890,100,9.133333,4.666667,0.300000
Lisbon,Sightseeing,Beach,Medium,0.640,1720,170,16.500000,8.000000,0.233333
London,Sightseeing,Sightseeing,High,0.370,780,110,10.800000,5.500000,0.277778
Nice,Beach,Sightseeing,Low,0.280,420,70,14.600000,7.666667,0.188889
Oslo,Outdoor,Sightseeing,High,0.540,1400,135,6.600000,6.166667,0.266667
Paris,Sightseeing,Sightseeing,Medium,0.290,490,85,11.500000,5.333333,0.322222
Prag,Party,Sightseeing,Low,0.300,530,80,8.700000,5.500000,0.255556
Reykjavik,Outdoor,Outdoor,High,0.929,2620,225,4.000000,5.166667,0.388889
Rimini,Party,Beach,Medium,0.290,480,70,12.833333,5.833333,0.222222
Rome,Sightseeing,Sightseeing,Medium,0.350,680,90,14.200000,7.333333,0.244444
Split,Beach,Party,Low,0.360,751,100,15.433333,7.500000,0.233333
Tirana,Outdoor,Beach,Low,0.460,1120,120,14.866667,6.833333,0.333333

In [15]:
test_set_clean = test_set_clean.reset_index()
test_set_clean

,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
0,Amsterdam,Sightseeing,Party,Low,0.320,610,100,9.766667,6.166667,0.311111
1,Barcelona,Beach,Sightseeing,Medium,0.390,840,100,14.900000,7.333333,0.166667
2,Budapest,Party,Sightseeing,Low,0.380,790,100,10.800000,6.833333,0.222222
3,Chamonix,Outdoor,Sightseeing,Medium,0.220,200,120,7.700000,5.833333,0.377778
4,Crete,Beach,Beach,Medium,0.704,1919,180,16.633333,7.833333,0.122222
5,Edinburgh,Outdoor,Sightseeing,Medium,0.493,1250,135,7.833333,5.166667,0.322222
6,Faro,Beach,Party,Low,0.660,1780,170,16.766667,8.833333,0.166667
7,Ibiza,Party,Beach,High,0.460,1100,125,16.066667,8.000000,0.188889
8,Krakow,Party,Sightseeing,Low,0.390,890,100,9.133333,4.666667,0.300000
9,Lisbon,Sightseeing,Beach,Medium,0.640,1720,170,16.500000,8.000000,0.233333
10,London,Sightseeing,Sightseeing,High,0.370,780,110,10.800000,5.500000,0.277778
11,Nice,Beach,Sightseeing,Low,0.280,420,70,14.600000,7.666667,0.188889
12,Oslo,Outdoor,Sightseeing,High,0.540,1400,135,6.600000,6.166667,0.266667
13,Paris,Sightseeing,Sightseeing,Medium,0.290,490,85,11.500000,5.333333,0.322222
14,Prag,Party,Sightseeing,Low,0.300,530,80,8.700000,5.500000,0.255556
15,Reykjavik,Outdoor,Outdoor,High,0.929,2620,225,4.000000,5.166667,0.388889
16,Rimini,Party,Beach,Medium,0.290,480,70,12.833333,5.833333,0.222222
17,Rome,Sightseeing,Sightseeing,Medium,0.350,680,90,14.200000,7.333333,0.244444
18,Split,Beach,Party,Low,0.360,751,100,15.433333,7.500000,0.233333
19,Tirana,Outdoor,Beach,Low,0.460,1120,120,14.866667,6.833333,0.333333

In [16]:
# filter for user category in both category columns
# watch out, user has to pass 'user_category' first!
test_set_clean = test_set_clean[(test_set_clean["Category"] == user_activity) | (test_set_clean["Category 2"] == user_activity)]
test_set_clean = test_set_clean.reset_index()
test_set_clean

,index,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
0,0,Amsterdam,Sightseeing,Party,Low,0.320,610,100,9.766667,6.166667,0.311111
1,1,Barcelona,Beach,Sightseeing,Medium,0.390,840,100,14.900000,7.333333,0.166667
2,2,Budapest,Party,Sightseeing,Low,0.380,790,100,10.800000,6.833333,0.222222
3,3,Chamonix,Outdoor,Sightseeing,Medium,0.220,200,120,7.700000,5.833333,0.377778
4,5,Edinburgh,Outdoor,Sightseeing,Medium,0.493,1250,135,7.833333,5.166667,0.322222
5,8,Krakow,Party,Sightseeing,Low,0.390,890,100,9.133333,4.666667,0.300000
6,9,Lisbon,Sightseeing,Beach,Medium,0.640,1720,170,16.500000,8.000000,0.233333
7,10,London,Sightseeing,Sightseeing,High,0.370,780,110,10.800000,5.500000,0.277778
8,11,Nice,Beach,Sightseeing,Low,0.280,420,70,14.600000,7.666667,0.188889
9,12,Oslo,Outdoor,Sightseeing,High,0.540,1400,135,6.600000,6.166667,0.266667
10,13,Paris,Sightseeing,Sightseeing,Medium,0.290,490,85,11.500000,5.333333,0.322222
11,14,Prag,Party,Sightseeing,Low,0.300,530,80,8.700000,5.500000,0.255556
12,17,Rome,Sightseeing,Sightseeing,Medium,0.350,680,90,14.200000,7.333333,0.244444

#### User parameters questionnaire (input)

In [17]:
preferences_dict = {
    user_prio1: {"weight": 30},
    user_prio2: {"weight": 25},
    user_prio3: {"weight": 20},
    user_prio4: {"weight": 15},
    user_prio5: {"weight": 10}
}

In [18]:
preferences_dict

{'Flight time': {'weight': 30},
 'Budget': {'weight': 25},
 'CO2': {'weight': 20},
 'Temperature': {'weight': 15},
 'Rain probability': {'weight': 10}}

In [19]:
# previous implementation (causes copy problems)
# df_scores = pd.DataFrame(columns=[test_set_clean.columns], index=test_set_clean.index).copy()
# df_scores[["City", "Category", "Category 2", "Budget"]] = test_set_clean[["City", "Category", "Category 2", "Budget"]].copy()

df_scores = test_set_clean.copy()
df_scores

,index,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
0,0,Amsterdam,Sightseeing,Party,Low,0.320,610,100,9.766667,6.166667,0.311111
1,1,Barcelona,Beach,Sightseeing,Medium,0.390,840,100,14.900000,7.333333,0.166667
2,2,Budapest,Party,Sightseeing,Low,0.380,790,100,10.800000,6.833333,0.222222
3,3,Chamonix,Outdoor,Sightseeing,Medium,0.220,200,120,7.700000,5.833333,0.377778
4,5,Edinburgh,Outdoor,Sightseeing,Medium,0.493,1250,135,7.833333,5.166667,0.322222
5,8,Krakow,Party,Sightseeing,Low,0.390,890,100,9.133333,4.666667,0.300000
6,9,Lisbon,Sightseeing,Beach,Medium,0.640,1720,170,16.500000,8.000000,0.233333
7,10,London,Sightseeing,Sightseeing,High,0.370,780,110,10.800000,5.500000,0.277778
8,11,Nice,Beach,Sightseeing,Low,0.280,420,70,14.600000,7.666667,0.188889
9,12,Oslo,Outdoor,Sightseeing,High,0.540,1400,135,6.600000,6.166667,0.266667
10,13,Paris,Sightseeing,Sightseeing,Medium,0.290,490,85,11.500000,5.333333,0.322222
11,14,Prag,Party,Sightseeing,Low,0.300,530,80,8.700000,5.500000,0.255556
12,17,Rome,Sightseeing,Sightseeing,Medium,0.350,680,90,14.200000,7.333333,0.244444

In [20]:
for x in ["CO2", "Flight time (min)", "Rain probability"]:
    for i in range(0, len(df_scores)):
        if test_set_clean.loc[i, x] <= test_set_clean[x].median():
            df_scores.loc[i, x] = 1
        else: 
            df_scores.loc[i, x] = 0

for y in ["Average Temp", "Sun hours per day"]:
    for j in range(0, len(df_scores)):
        if test_set_clean.loc[j, y] >= test_set_clean[y].median():
            df_scores.loc[j, y] = 1
        else: 
            df_scores.loc[j, y] = 0

replace_dic = {"Low": "1", "Medium": 0.5, "High": 0}
df_scores["Budget"].replace(replace_dic, inplace = True)

df_scores

,index,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability
0,0,Amsterdam,Sightseeing,Party,1,1.0,610,1,0.0,1.0,0.0
1,1,Barcelona,Beach,Sightseeing,0.5,0.0,840,1,1.0,1.0,1.0
2,2,Budapest,Party,Sightseeing,1,0.0,790,1,1.0,1.0,1.0
3,3,Chamonix,Outdoor,Sightseeing,0.5,1.0,200,0,0.0,0.0,0.0
4,5,Edinburgh,Outdoor,Sightseeing,0.5,0.0,1250,0,0.0,0.0,0.0
5,8,Krakow,Party,Sightseeing,1,0.0,890,1,0.0,0.0,0.0
6,9,Lisbon,Sightseeing,Beach,0.5,0.0,1720,0,1.0,1.0,1.0
7,10,London,Sightseeing,Sightseeing,0,1.0,780,0,1.0,0.0,0.0
8,11,Nice,Beach,Sightseeing,1,1.0,420,1,1.0,1.0,1.0
9,12,Oslo,Outdoor,Sightseeing,0,0.0,1400,0,0.0,1.0,1.0
10,13,Paris,Sightseeing,Sightseeing,0.5,1.0,490,1,1.0,0.0,0.0
11,14,Prag,Party,Sightseeing,1,1.0,530,1,0.0,0.0,1.0
12,17,Rome,Sightseeing,Sightseeing,0.5,1.0,680,1,1.0,1.0,1.0

In [21]:
score_budget = preferences_dict["Budget"]["weight"] * df_scores["Budget"]
score_flight_time = preferences_dict["Flight time"]["weight"] * df_scores["Flight time (min)"]
score_co2 = preferences_dict["CO2"]["weight"] * df_scores["CO2"]
score_temp = preferences_dict["Temperature"]["weight"] * df_scores["Average Temp"]
score_rain = preferences_dict["Rain probability"]["weight"] * df_scores["Rain probability"]

df_scores["Score"] = pd.concat([score_budget, score_flight_time, score_co2, score_temp, score_rain], axis=1).sum(axis=1)
df_scores

,index,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability,Score
0,0,Amsterdam,Sightseeing,Party,1,1.0,610,1,0.0,1.0,0.0,50.0
1,1,Barcelona,Beach,Sightseeing,0.5,0.0,840,1,1.0,1.0,1.0,55.0
2,2,Budapest,Party,Sightseeing,1,0.0,790,1,1.0,1.0,1.0,55.0
3,3,Chamonix,Outdoor,Sightseeing,0.5,1.0,200,0,0.0,0.0,0.0,20.0
4,5,Edinburgh,Outdoor,Sightseeing,0.5,0.0,1250,0,0.0,0.0,0.0,0.0
5,8,Krakow,Party,Sightseeing,1,0.0,890,1,0.0,0.0,0.0,30.0
6,9,Lisbon,Sightseeing,Beach,0.5,0.0,1720,0,1.0,1.0,1.0,25.0
7,10,London,Sightseeing,Sightseeing,0,1.0,780,0,1.0,0.0,0.0,35.0
8,11,Nice,Beach,Sightseeing,1,1.0,420,1,1.0,1.0,1.0,75.0
9,12,Oslo,Outdoor,Sightseeing,0,0.0,1400,0,0.0,1.0,1.0,10.0
10,13,Paris,Sightseeing,Sightseeing,0.5,1.0,490,1,1.0,0.0,0.0,65.0
11,14,Prag,Party,Sightseeing,1,1.0,530,1,0.0,0.0,1.0,60.0
12,17,Rome,Sightseeing,Sightseeing,0.5,1.0,680,1,1.0,1.0,1.0,75.0

In [22]:
# sort according to Score
df_scores.sort_values(by=['Score'], ascending = False, inplace = True)
df_scores["index"] = df_scores.reset_index().index
df_scores["index"] += 1
df_scores.rename({"index": "Rank"}, axis=1, inplace=True)
df_scores = df_scores.set_index("Rank")
df_scores

,City,Category,Category 2,Budget,CO2,Distance (km),Flight time (min),Average Temp,Sun hours per day,Rain probability,Score
Rank,,,,,,,,,,,
1,Nice,Beach,Sightseeing,1,1.0,420,1,1.0,1.0,1.0,75.0
2,Rome,Sightseeing,Sightseeing,0.5,1.0,680,1,1.0,1.0,1.0,75.0
3,Paris,Sightseeing,Sightseeing,0.5,1.0,490,1,1.0,0.0,0.0,65.0
4,Prag,Party,Sightseeing,1,1.0,530,1,0.0,0.0,1.0,60.0
5,Barcelona,Beach,Sightseeing,0.5,0.0,840,1,1.0,1.0,1.0,55.0
6,Budapest,Party,Sightseeing,1,0.0,790,1,1.0,1.0,1.0,55.0
7,Amsterdam,Sightseeing,Party,1,1.0,610,1,0.0,1.0,0.0,50.0
8,London,Sightseeing,Sightseeing,0,1.0,780,0,1.0,0.0,0.0,35.0
9,Krakow,Party,Sightseeing,1,0.0,890,1,0.0,0.0,0.0,30.0
10,Lisbon,Sightseeing,Beach,0.5,0.0,1720,0,1.0,1.0,1.0,25.0
11,Chamonix,Outdoor,Sightseeing,0.5,1.0,200,0,0.0,0.0,0.0,20.0
12,Oslo,Outdoor,Sightseeing,0,0.0,1400,0,0.0,1.0,1.0,10.0
13,Edinburgh,Outdoor,Sightseeing,0.5,0.0,1250,0,0.0,0.0,0.0,0.0

In [23]:
print("Your top 3 travel locations are: \n", df_scores.loc[1:3, ["City", "Score"]])

Your top 3 travel locations are:
        City  Score
Rank
1      Nice   75.0
2      Rome   75.0
3     Paris   65.0

In [ ]:
greeting = "Have a great vacation!"